"""
report.py
---------
Turns raw Bug / FixResult data into human-readable markdown: a full
scan report, and a GitHub-PR-ready description.
"""

SEVERITY_EMOJI = {"high": "🔴", "medium": "🟡", "low": "🔵"}


def bug_report_markdown(results_by_file, files_scanned, total_bugs):
    lines = []
    lines.append("# Bug Hunter Report\n")
    lines.append(f"Scanned **{files_scanned}** Python file(s), found **{total_bugs}** issue(s).\n")

    if not results_by_file:
        lines.append("No issues found. 🎉\n")
        return "\n".join(lines)

    # Summary table
    lines.append("## Summary\n")
    lines.append("| File | Issues |")
    lines.append("|---|---|")
    for filepath, data in results_by_file.items():
        lines.append(f"| `{filepath}` | {len(data['bugs'])} |")
    lines.append("")

    # Detail per file
    for filepath, data in results_by_file.items():
        lines.append(f"## `{filepath}`\n")
        for bug in sorted(data["bugs"], key=lambda b: b.line):
            emoji = SEVERITY_EMOJI.get(bug.severity, "")
            fix_tag = "✅ auto-fixable" if bug.auto_fixable else "✋ manual review needed"
            lines.append(f"### {emoji} Line {bug.line}: {bug.title} ({fix_tag})\n")
            lines.append(f"```python\n{bug.code_snippet}\n```\n")
            lines.append(f"{bug.message}\n")
            lines.append(f"**Suggested fix:** {bug.suggested_fix_note}\n")

    return "\n".join(lines)


def pr_body_markdown(results_by_file, fix_results_by_file, files_scanned, total_bugs):
    total_fixed = sum(
        1 for results in fix_results_by_file.values() for r in results if r.applied
    )
    total_manual = total_bugs - total_fixed

    lines = []
    lines.append("## 🤖 Automated Bug Fixes\n")
    lines.append(
        f"This PR was generated by Bug Hunter after scanning {files_scanned} "
        f"Python file(s). It found **{total_bugs}** issue(s): "
        f"**{total_fixed}** were auto-fixed here, "
        f"**{total_manual}** need manual review (listed below, not changed).\n"
    )

    lines.append("### ✅ Auto-fixed\n")
    any_fixed = False
    for filepath, fix_results in fix_results_by_file.items():
        for r in fix_results:
            if r.applied:
                any_fixed = True
                lines.append(
                    f"- **`{filepath}:{r.bug.line}`** — {r.bug.title}. "
                    f"{r.bug.suggested_fix_note}"
                )
    if not any_fixed:
        lines.append("- (none)")
    lines.append("")

    lines.append("### ✋ Needs manual review (not changed)\n")
    any_manual = False
    for filepath, data in results_by_file.items():
        fixed_lines = {
            r.bug.line for r in fix_results_by_file.get(filepath, []) if r.applied
        }
        for bug in data["bugs"]:
            if bug.line not in fixed_lines:
                any_manual = True
                lines.append(
                    f"- **`{filepath}:{bug.line}`** — {bug.title}: {bug.suggested_fix_note}"
                )
    if not any_manual:
        lines.append("- (none)")
    lines.append("")

    lines.append(
        "\n---\n*Generated by Bug Hunter — deterministic AST-based static "
        "analysis, no LLM involved. Review the diff before merging, as with "
        "any automated change.*"
    )

    return "\n".join(lines)
